version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 nexus:
  build: ./nexus
  ports:
    - "18081:8081"
  networks:
    - prodnetwork

 jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  networks:
    - prodnetwork
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /opt/jenkins/:/var/lib/jenkins/
  depends_on:
    - nexus
    - sonar
    - jmeter
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432

 sonar:
  image: sonarqube
  ports:
   - "19000:9000"
   - "19092:9092"
   - "5432:5432"
  networks:
    - prodnetwork
  #depends_on:
    #- sonardb
  #environment:
   #- SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
   #- SONARQUBE_JDBC_USERNAME=sonar
   #- SONARQUBE_JDBC_PASSWORD=sonar
 sonardb:
  networks:
    - prodnetwork
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  volumes:
    - /opt/postgres/data:/var/lib/postgresql/data

 jmeter:
  hostname: jmeter
  networks:
    - prodnetwork
  build: ./jmeter
  volumes:
    - /opt/jmeter/results:/results
    - /opt/jmeter/script:/scripts


